const fs = require('fs');
const path = require('path');

const docsDir = path.join(__dirname, '../docs');
if (!fs.existsSync(docsDir)) {
  fs.mkdirSync(docsDir);
}

const docs = {
  'PROJECT_OVERVIEW.md': `# PsychoMetric Pro - Project Overview\n\n## Purpose\nPsychoMetric Pro is a premium, evidence-based personality assessment platform built to deliver a 50-question OCEAN (Big Five) assessment. It guides participants through an intuitive intake, processes secure payments via Razorpay, administers the assessment with deterministic scoring, and generates a personalized report with PDF export.\n\n## Target Users\nIndividuals seeking self-development and clarity on their behavioral tendencies, as well as professionals and leaders looking to understand their communication and stress management styles.\n\n## Core Features\n1. **Premium Landing & Checkout**: Conversion-optimized entry flow with secure Razorpay payment gateway.\n2. **50-Question OCEAN Assessment**: Research-backed psychometric evaluation.\n3. **Deterministic Scoring Engine**: Real-time evaluation of 5 traits with reverse scoring and normalization.\n4. **Instant Personalized Report & PDF**: Beautiful on-screen results and a professionally formatted, downloadable PDF generated via React-PDF.\n5. **Admin Dashboard**: Secure management interface for monitoring participants, payments, and generated reports.\n\n## Technology Stack\n- **Framework**: Next.js 16 (App Router)\n- **Language**: TypeScript\n- **Styling**: Tailwind CSS v4, Plus Jakarta Sans\n- **Database**: PostgreSQL (via Prisma ORM)\n- **Payment**: Razorpay\n- **PDF Generation**: @react-pdf/renderer\n- **Email**: Resend\n- **Security**: bcryptjs, secure cookies, zod validation\n`,
  'ARCHITECTURE.md': `# Architecture\n\n## Frontend\nBuilt with Next.js App Router (React 19). Uses Server Components for static layouts and Client Components for interactive states (assessment flow, forms). Styling is powered by Tailwind CSS v4.\n\n## Backend & APIs\nNext.js Route Handlers (\`/api/*\`) act as the backend. They handle form submissions, Razorpay order creation, payment verification via HMAC signatures, scoring logic, and PDF generation.\n\n## Database\nPostgreSQL managed via Prisma ORM. Handles participants, assessments, payments, results, and JSON reports.\n\n## External Services\n- **Razorpay**: For secure INR transactions.\n- **Resend**: For transactional email delivery.\n- **Vercel**: Deployment platform.\n`,
  'USER_FLOW.md': `# User Flow\n\n1. **Landing Page**: Participant learns about the assessment.\n2. **Participant Details**: Enters Name, Email, Phone.\n3. **Payment Initiation**: Clicks pay, system generates a Razorpay order.\n4. **Secure Checkout**: Razorpay modal opens, user pays ₹99.\n5. **Verification**: System verifies Razorpay signature and unlocks questions.\n6. **Assessment**: User answers 50 questions (5 per page, 10 pages).\n7. **Submission**: Answers are scored deterministically.\n8. **Report**: User views personalized results on-screen.\n9. **PDF Export**: User can download a structured PDF report.\n`,
  'ADMIN_FLOW.md': `# Admin Flow\n\n1. **Authentication**: Admin logs in via \`/admin/login\` using a secure password verified by bcrypt. Session is stored in an encrypted HttpOnly cookie.\n2. **Dashboard**: High-level metrics (Total participants, paid assessments, completion rate).\n3. **Participants**: View all registered users and their status.\n4. **Payments**: Audit log of Razorpay transactions.\n5. **Reports**: Access generated user profiles.\n6. **Evidence**: Exportable CSV mapping participants to Razorpay IDs.\n7. **Reset Control**: Secure route to reset the database (preserves admin auth, wipes user data).\n`,
  'API_REFERENCE.md': `# API Reference\n\n- \`POST /api/assessment/start\`: Creates a participant and pending assessment.\n- \`POST /api/payment/create-order\`: Generates a Razorpay order ID.\n- \`POST /api/payment/verify\`: Validates Razorpay HMAC signature and unlocks assessment.\n- \`GET /api/assessment/[token]/questions\`: Retrieves 50 questions if payment is SUCCESS.\n- \`POST /api/assessment/[token]/submit\`: Submits answers, runs scoring engine, saves report.\n- \`GET /api/report/[id]/pdf\`: Generates and returns the PDF buffer.\n- \`POST /api/admin/login\`: Authenticates admin.\n- \`POST /api/admin/logout\`: Clears session.\n- \`POST /api/admin/reset\`: Hard resets database (requires admin session).\n`,
  'DATABASE.md': `# Database Schema\n\n- **Participant**: \`id\`, \`name\`, \`email\`, \`phone\`\n- **Assessment**: \`id\`, \`status\` (CREATED, PAYMENT_PENDING, COMPLETED), timestamps.\n- **Payment**: \`id\`, \`razorpayOrderId\`, \`razorpayPaymentId\`, \`amount\`, \`status\`.\n- **Response**: Stores individual question answers (1-5).\n- **Result**: Stores raw 0-100 normalized scores for the 5 traits.\n- **Report**: Stores the generated JSON content (classifications, strengths, action plan).\n`,
  'SCORING_AND_ASSESSMENT.md': `# Scoring and Assessment\n\n- **Questions**: Exactly 50 questions, 10 per OCEAN trait.\n- **Scale**: 5-point Likert scale (1 = Strongly Disagree, 5 = Strongly Agree).\n- **Reverse Scoring**: Specific questions are marked with \`reverse: true\`. The engine inverts these scores (e.g., 5 becomes 1).\n- **Normalization**: Raw scores are summed per trait and mapped to a 0-100 percentage.\n- **Classification**: Scores are categorized as LOW (0-33), MEDIUM (34-66), or HIGH (67-100) to pull deterministic interpretation text from the dictionary.\n`,
  'REPORT_AND_PDF.md': `# Report and PDF\n\n## Web Report\nThe web report (\`/report/[id]\`) displays a circular radar chart, trait breakdowns, strengths, communication styles, and action plans based on the generated JSON.\n\n## PDF Export\nThe PDF is generated dynamically using \`@react-pdf/renderer\`. It includes:\n- Cover page with participant name.\n- Executive summary.\n- Detailed breakdowns for Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism.\n- Final action plan.\nReturns as \`application/pdf\` with correct headers.\n`,
  'SECURITY.md': `# Security\n\n- **Payments**: Razorpay signatures are verified server-side using \`crypto.createHmac\` to prevent spoofing.\n- **Admin Auth**: Admin password is hashed via \`bcryptjs\`. Sessions use \`cookies().set\` with \`httpOnly\`, \`secure\` (in prod), \`sameSite: 'strict'\`, and an expiration time. Depends on \`ADMIN_SESSION_SECRET\`.\n- **Data Privacy**: No user can view another's assessment without the unguessable UUID token.\n- **Rate Limiting/Validation**: \`zod\` is used across all API routes to prevent malformed payloads.\n`,
  'TESTING.md': `# Testing\n\n- **Framework**: Jest & ts-jest.\n- **Suites Passed**: 4 suites, 67 tests.\n- **Coverage**: Covers Razorpay signature logic, the scoring engine (reverse scoring, normalization, deterministic output), admin metrics aggregation, and response quality checks.\n- **Typecheck**: \`npx tsc --noEmit\` passes with 0 errors.\n- **Build**: \`next build\` successfully compiles all routes.\n`,
  'DEPLOYMENT.md': `# Deployment\n\n- **Platform**: Designed for Vercel.\n- **Database**: PostgreSQL (e.g., Supabase or Neon), configured via \`DATABASE_URL\`.\n- **Environment Variables (Required)**:\n  - \`DATABASE_URL\` (Prisma PG connection)\n  - \`NEXT_PUBLIC_RAZORPAY_KEY_ID\` (Public)\n  - \`RAZORPAY_KEY_SECRET\` (Secret)\n  - \`ADMIN_PASSWORD_HASH\` (Generated via bcrypt)\n  - \`ADMIN_SESSION_SECRET\` (32+ char random string)\n  - \`RESEND_API_KEY\` (Secret)\n`,
  'LIMITATIONS_AND_FUTURE_SCOPE.md': `# Limitations and Future Scope\n\n## Limitations\n- The application currently assumes INR currency for Razorpay hardcoded in the create-order route.\n- PDF generation via React-PDF can be CPU intensive under extreme load; serverless function timeouts on Vercel hobby tier may occur if the PDF exceeds 10s generation time.\n\n## Future Scope\n- Implement webhooks for Razorpay to handle asynchronous payment captures in case of dropped connections.\n- Add internationalization (i18n) for non-English speakers.\n- Add bulk export of full assessment data (not just evidence mappings) for psychological research.\n`,
  'ASSIGNMENT_MAPPING.md': `# Assignment Mapping\n\n| Assignment Requirement | Implementation | Evidence/File | Status |\n|---|---|---|---|\n| Full Assessment Flow | Implemented | \`/assessment\`, \`api/assessment/start\` | ✅ Complete |\n| 50 Questions | Implemented | \`src/lib/questions.ts\` | ✅ Complete |\n| OCEAN Scoring | Implemented | \`src/lib/scoring/engine.ts\` | ✅ Complete |\n| Razorpay Integration | Implemented | \`api/payment/create-order\`, \`api/payment/verify\` | ✅ Complete |\n| PDF Generation | Implemented | \`api/report/[id]/pdf/route.ts\` | ✅ Complete |\n| Admin Dashboard | Implemented | \`/admin/...\`, \`api/admin/...\` | ✅ Complete |\n| Secure Auth | Implemented | \`src/lib/auth.ts\` | ✅ Complete |\n`
};

for (const [filename, content] of Object.entries(docs)) {
  fs.writeFileSync(path.join(docsDir, filename), content);
  console.log(`Created ${filename}`);
}
